/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalmanagement;


import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;


/**
 *
 * @author Magcalas
 */
public class RENT_RETURN extends javax.swing.JFrame {
    public static String[] CarPlate = {"Plate No.","GMK4567","DAF5208","FOI6309","JKQ4230","PAX3402","CPY2994","UZC6965","STL8196","BUI8515","SNS1943","HFQ8671","NNL902"};
    public static String CarPlate1;
    public static DecimalFormat df = new DecimalFormat("00.00");
    public static Double calcu = 0.0;
    public static Double inputValue = 0.0;
    public static Double total = calcu - inputValue;
    public static String dpay;
    public static Double rentday = 0.0;

    public static int days;
    
    public RENT_RETURN() {
        initComponents();
        jDateChooser2PropertyChange(null);
        this.setTitle("CJ Car Rental Services");
        Image icon = new ImageIcon(this.getClass().getResource("/Logopic/Lamborghini.png")).getImage();
        this.setIconImage(icon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Carlogo = new javax.swing.JLabel();
        CJ = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        rentablebtn = new javax.swing.JButton();
        rentbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        returncar_lbl = new javax.swing.JLabel();
        return1 = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rentacar_lbl = new javax.swing.JLabel();
        carplate1_lbl = new javax.swing.JLabel();
        name1_lbl = new javax.swing.JLabel();
        date_lbl = new javax.swing.JLabel();
        duedate_lbl = new javax.swing.JLabel();
        CarBrand = new javax.swing.JComboBox<>();
        savebtn1 = new javax.swing.JButton();
        clearbtn1 = new javax.swing.JButton();
        namefield1 = new javax.swing.JTextField();
        rentacar_lbl1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        duedate_lbl1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        dpfield = new javax.swing.JTextField();
        CarPic = new javax.swing.JLabel();
        carplate1_lbl1 = new javax.swing.JLabel();
        carplate1_lbl2 = new javax.swing.JLabel();
        numberplate1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        Carlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logopic/Blue_and_Red_Minimalist_Car_Detailing_Logo-removebg-preview.png"))); // NOI18N
        Carlogo.setText("Carlogo");
        Carlogo.setAutoscrolls(true);

        CJ.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        CJ.setText("CJ Car Rental Services");
        CJ.setAutoscrolls(true);

        logoutbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logoutbtn.setText("LOG OUT");
        logoutbtn.setAutoscrolls(true);
        logoutbtn.setContentAreaFilled(false);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        homebtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        homebtn.setText("HOME");
        homebtn.setAutoscrolls(true);
        homebtn.setContentAreaFilled(false);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        rentablebtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rentablebtn.setText("RENTABLES");
        rentablebtn.setAutoscrolls(true);
        rentablebtn.setContentAreaFilled(false);
        rentablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentablebtnActionPerformed(evt);
            }
        });

        rentbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rentbtn.setText("RENT & RETURN A CAR");
        rentbtn.setAutoscrolls(true);
        rentbtn.setContentAreaFilled(false);
        rentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Carlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homebtn)
                .addGap(41, 41, 41)
                .addComponent(rentablebtn)
                .addGap(61, 61, 61)
                .addComponent(rentbtn)
                .addGap(55, 55, 55)
                .addComponent(logoutbtn)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CJ)
                    .addComponent(homebtn)
                    .addComponent(rentablebtn)
                    .addComponent(rentbtn)
                    .addComponent(logoutbtn))
                .addContainerGap())
        );

        jPanel4.setAutoscrolls(true);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Brand", "Name", "Return Date"
            }
        ));
        jTable2.setDragEnabled(true);
        jScrollPane3.setViewportView(jTable2);

        returncar_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        returncar_lbl.setText("RETURN CAR");

        return1.setText("Return");
        return1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return1ActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(return1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(deletebtn)
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(returncar_lbl)
                        .addGap(184, 184, 184))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(returncar_lbl)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(return1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletebtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setAutoscrolls(true);

        rentacar_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rentacar_lbl.setText("Car Rented");

        carplate1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        carplate1_lbl.setText("Car Brand:");

        name1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name1_lbl.setText("Customer Name:");

        date_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        date_lbl.setText("Date:");

        duedate_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duedate_lbl.setText("DownPayment:");

        CarBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "FORD RANGER RAPTOR", "MITSHUBISHI MONTERO SPORTS", "TOYOTA LAND CRUISER", "TOYOTA HILUX CONQUEST", "HONDA CIVIC TYPE-R", "NISSAN ALMERA", "FORD S-MAX", "TOYOTA VIOS", "TOYOTA HIACE", "VOLKSWAGEN VWT1|1950", "HYUNDAI STAREX", "FOTON TRAVELLER XL" }));
        CarBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CarBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarBrandActionPerformed(evt);
            }
        });

        savebtn1.setText("Save");
        savebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtn1ActionPerformed(evt);
            }
        });

        clearbtn1.setText("Clear");
        clearbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtn1ActionPerformed(evt);
            }
        });

        namefield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefield1ActionPerformed(evt);
            }
        });

        rentacar_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rentacar_lbl1.setText("RENT A CAR");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Brand", "Car Plate No.", "Customer", "Date", "Due Date", "DPayment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setDragEnabled(true);
        jScrollPane2.setViewportView(jTable1);

        duedate_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duedate_lbl1.setText("Due Date:");

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });

        dpfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpfieldActionPerformed(evt);
            }
        });

        CarPic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        carplate1_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        carplate1_lbl1.setText("Plate No.:");

        carplate1_lbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        carplate1_lbl2.setText("Car:");

        numberplate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numberplate1.setText("Plate No.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carplate1_lbl)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(name1_lbl)
                                            .addComponent(date_lbl)
                                            .addComponent(duedate_lbl1)
                                            .addComponent(duedate_lbl))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(namefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dpfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(savebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clearbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberplate1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carplate1_lbl2)
                                    .addComponent(CarPic, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rentacar_lbl)
                                    .addComponent(rentacar_lbl1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carplate1_lbl1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rentacar_lbl1)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carplate1_lbl)
                            .addComponent(CarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name1_lbl)
                            .addComponent(namefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_lbl))
                                .addGap(18, 18, 18)
                                .addComponent(duedate_lbl1)
                                .addGap(18, 18, 18)
                                .addComponent(duedate_lbl))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dpfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearbtn1)
                            .addComponent(savebtn1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(carplate1_lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberplate1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carplate1_lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CarPic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(rentacar_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public Double DayGap(){
        Double price2 = 0.0;
        //String CarName1;
        Double[] price1 = {0.0,3500.00,3500.00,120000.00,4000.00,5206.00,2000.00,2500.00,2500.00,4000.00,3931.52,4000.00,7000.00};
        if(CarBrand.getSelectedItem().equals("FORD RANGER RAPTOR")){
             price2 = price1[1];
             CarPlate1 = CarPlate[1];
        }
        else if(CarBrand.getSelectedItem().equals("MITSHUBISHI MONTERO SPORTS")){
             price2 = price1[2];
             CarPlate1 = CarPlate[2];
        }
        else if(CarBrand.getSelectedItem().equals("TOYOTA LAND CRUISER")){
             price2 = price1[3];
             CarPlate1 = CarPlate[3];
        }
        else if(CarBrand.getSelectedItem().equals("TOYOTA HILUX CONQUEST")){
             price2 = price1[4];
             CarPlate1 = CarPlate[4];
        }
        else if(CarBrand.getSelectedItem().equals("HONDA CIVIC TYPE-R")){
             price2 = price1[5];
             CarPlate1 = CarPlate[5];
        }
        else if(CarBrand.getSelectedItem().equals("NISSAN ALMERA")){
             price2 = price1[6];
             CarPlate1 = CarPlate[6];
        }
        else if(CarBrand.getSelectedItem().equals("FORD S-MAX")){
             price2 = price1[7];
             CarPlate1 = CarPlate[7];
        }
        else if(CarBrand.getSelectedItem().equals("TOYOTA VIOS")){
             price2 = price1[8];
             CarPlate1 = CarPlate[8];
        }
        else if(CarBrand.getSelectedItem().equals("TOYOTA HIACE")){
             price2 = price1[9];
             CarPlate1 = CarPlate[9];
        }
        else if(CarBrand.getSelectedItem().equals("VOLKSWAGEN VWT1|1950")){
             price2 = price1[10];
             CarPlate1 = CarPlate[10];
        }
        else if(CarBrand.getSelectedItem().equals("HYUNDAI STAREX")){
             price2 = price1[11];
             CarPlate1 = CarPlate[11];
        }
        else if(CarBrand.getSelectedItem().equals("FOTON TRAVELLER XL")){
             price2 = price1[12];
             CarPlate1 = CarPlate[12];
        }
        return price2;
    }
    public Double renting(Double price3){
      LocalDate startDate = jDateChooser1.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
      LocalDate endDate = jDateChooser2.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
      dpay = dpfield.getText();
      rentday = price3;
      //Double calcu = 0.0;
      //Double inputValue = 0.0;
      //Double total = calcu - inputValue;
      

        days = (int) ChronoUnit.DAYS.between(startDate, endDate);
            if(days >= 1 && days <= 6){
                calcu = price3 * days;
                inputValue = Double.valueOf(dpay);               
                total = calcu - inputValue;
                JOptionPane.showMessageDialog(null, "Rent per day: ₱"+ df.format(price3) +
                                                   "\nTotal Amount to pay: ₱"+ df.format(calcu) + 
                                                   "\nYour Downpayment is: ₱" + dpay + 
                                                   "\nYour remaining balance is: ₱" + df.format(total) + 
                                                   "\nDay Gap: "+ days ,"NOTICE",JOptionPane.INFORMATION_MESSAGE);                      
            }
            else if(days >= 7 && days <= 14){
                Double discount = price3 * 0.2;
                Double discount1 = price3 - discount;
                calcu = discount * days; 
                inputValue = Double.valueOf(dpay);
                total = calcu - inputValue;
                JOptionPane.showMessageDialog(null, "Original rent rate: ₱"+ df.format(price3) + 
                                                    "\nRent per day(20% discount): ₱"+ df.format(discount1) +
                                                    "\nTotal Amount to pay: ₱"+ df.format(calcu) + 
                                                    "\nYour Downpayment is: ₱" + dpay + 
                                                    "\nYour remaining balance is: ₱" + df.format(total) + 
                                                    "\nDay Gap: "+ days ,"NOTICE",JOptionPane.INFORMATION_MESSAGE);
            }
            else if(days >= 15 && days <= 31 || days > 31){
                Double discount = price3 * 0.4;
                Double discount1 = price3 - discount;
                calcu = discount * days;
                inputValue = Double.valueOf(dpay);
                total = calcu - inputValue;
                JOptionPane.showMessageDialog(null, "Original rent rate: ₱"+ df.format(price3) + 
                                                   "\nRent per day(40% discount): ₱"+ df.format(discount1) +
                                                    "\nTotal Amount to pay: ₱"+ df.format(calcu) + 
                                                    "\nYour Downpayment is: ₱" + dpay + 
                                                    "\nYour remaining balance is: ₱" + df.format(total) + 
                                                    "\nDay Gap: "+ days ,"NOTICE",JOptionPane.INFORMATION_MESSAGE);           
            }
            else if(days == 0){
                calcu = price3 * days;
                inputValue = Double.valueOf(dpay);               
                total = calcu - inputValue;
                JOptionPane.showMessageDialog(null, "Rent per day: ₱"+ df.format(price3) +
                                                   "\nTotal Amount to pay: ₱"+ df.format(price3) + 
                                                   "\nYour Downpayment is: ₱" + dpay + 
                                                   "\nYour remaining balance is: ₱" + df.format(total) + 
                                                   "\nDay Gap: "+ days ,"NOTICE",JOptionPane.INFORMATION_MESSAGE);   
            }
            
        try {
            File path = new File("RENT_CAR.txt");
            if (!path.exists()) {
                boolean success = path.createNewFile();
            if (!success) {
            JOptionPane.showMessageDialog(null, "Could not create the file: RENT_CAR.txt", "Error", JOptionPane.ERROR_MESSAGE);
            
            }
        }
             FileWriter filewriter = new FileWriter(path.getAbsoluteFile(),true);
             BufferedWriter bufferedwriter = new BufferedWriter(filewriter);
             bufferedwriter.append("\n///////////////////////");
             bufferedwriter.append("\nCJ Car Rental Services");
             bufferedwriter.append("\n   (Rent a Car)");
             bufferedwriter.append("\n///////////////////////");
             bufferedwriter.append("\nCustomer Name: " + namefield1.getText());
             bufferedwriter.append("\nCar Brand: " + CarBrand.getSelectedItem().toString());
             bufferedwriter.append("\nPlate No.: " + numberplate1.getText());
             bufferedwriter.append("\nDownpayment: ₱" + dpay);
             bufferedwriter.append("\nRemaining Balance: ₱" + total);
             bufferedwriter.append("\n///////////////////////\n");            
             bufferedwriter.close();
             
    } catch (IOException e) {
    JOptionPane.showMessageDialog(null, "Could not write to the file: RENT_CAR.txt", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
    
    }
        return total;
    }
    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        int respond = JOptionPane.showConfirmDialog(null, "Do you wish to exit?","Notice",JOptionPane.YES_NO_OPTION);

        if(respond == JOptionPane.YES_OPTION){
            this.dispose();
            JOptionPane.showConfirmDialog(null, "THANK YOU FOR USING OUR JAVA MENU SYSTEM","Notice",JOptionPane.YES_NO_OPTION);
            LOGIN login = new LOGIN();
            login.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        if(evt.getSource()==homebtn){
            this.dispose();
            HOME home = new HOME();
            home.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_homebtnActionPerformed

    private void rentablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentablebtnActionPerformed
        if(evt.getSource()== rentablebtn){
            this.dispose();
            RENTABLES rentables = new RENTABLES();
            rentables.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_rentablebtnActionPerformed

    private void rentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentbtnActionPerformed
        if(evt.getSource()==rentbtn){
            this.dispose();
            RENT_RETURN rent = new RENT_RETURN();
            rent.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_rentbtnActionPerformed

    private void return1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return1ActionPerformed
        if (jTable1.getSelectedRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Please select a row in [Car Rented Table] before returning.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }

        Double remainblnc1 = 0.0;
        Double remainblnc2 = remainblnc1 - total;

        boolean validInput = false;
        do {
            try {
                String remainblnc = JOptionPane.showInputDialog(null, "The Car has been returned" + "\nRemaining balance: ₱" + df.format(total), "NOTICE", JOptionPane.OK_CANCEL_OPTION);
                remainblnc1 = Double.parseDouble(remainblnc);
                remainblnc2 = remainblnc1 - total;
                validInput = true;
            } 
            catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid number.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } while(!validInput);

        JOptionPane.showMessageDialog(null, "Paid: ₱" + df.format(remainblnc1) 
                                          + "\nChange: ₱" + df.format(remainblnc2) 
                                          + "\nThank you for renting our vehicles!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);

    try {
         File path = new File("RETURN_CAR.txt");
        if(!path.exists()){ 
              path.createNewFile();
    }
        FileWriter filewriter = new FileWriter(path.getAbsoluteFile(),true);
        BufferedWriter bufferedwriter = new BufferedWriter(filewriter);
        bufferedwriter.append("\n///////////////////////");
        bufferedwriter.append("\nCJ Car Rental Services");
        bufferedwriter.append("\n  (Return a Car)");
        bufferedwriter.append("\n///////////////////////");
        bufferedwriter.append("\nCustomer Name: " + jTable1.getValueAt(jTable1.getSelectedRow(), 2) 
                            + "\nCar Brand: " + jTable1.getValueAt(jTable1.getSelectedRow(), 0)
                            + "\nPlate No.: " + jTable1.getValueAt(jTable1.getSelectedRow(), 1)  //jTable1.getValueAt(jTable1.getSelectedRow(), 0) 
                            + "\nPay: ₱" + df.format(remainblnc1)
                            + "\nChange: ₱" + df.format(remainblnc2)); 
        bufferedwriter.append("\n///////////////////////\n");
        bufferedwriter.close();
    } catch (IOException e) {
        e.printStackTrace();
    }

    DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
    model2.addRow(new Object[]{
        jTable1.getValueAt(jTable1.getSelectedRow(), 0),
        jTable1.getValueAt(jTable1.getSelectedRow(), 1),
        jTable1.getValueAt(jTable1.getSelectedRow(), 3)
    });

    DefaultTableModel model3 = (DefaultTableModel) jTable1.getModel();
    model3.removeRow(jTable1.getSelectedRow());

    }//GEN-LAST:event_return1ActionPerformed

    private void namefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefield1ActionPerformed
        
    }//GEN-LAST:event_namefield1ActionPerformed

    private void clearbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtn1ActionPerformed
        CarBrand.setSelectedIndex(0);
        namefield1.setText(" ");
        jDateChooser1.setCalendar(null);
        jDateChooser2.setCalendar(null);
        dpfield.setText("");
    }//GEN-LAST:event_clearbtn1ActionPerformed

    private void savebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtn1ActionPerformed
       
        if(CarBrand.getSelectedIndex() > 0){
        Double rentalPrice = DayGap();// get the rental price for the selected car
        renting(rentalPrice); // call the renting() method with the rental price as an argument
        SimpleDateFormat dFormat = new SimpleDateFormat("MMM-dd-yyyy");
        String date = dFormat.format(jDateChooser1.getDate());
        String date2 = dFormat.format(jDateChooser2.getDate());
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{CarBrand.getSelectedItem(),
                                  numberplate1.getText(),
                                  namefield1.getText(),
                                  date, 
                                  date2,    
                                  dpfield.getText(),                                                                        
        });
        clearbtn1ActionPerformed(evt);
      try {
            FileWriter fileWriter = new FileWriter("Rent_Info.txt", true);
            if (total > 0) {
                fileWriter.write(namefield1.getText() + " - Total amount to pay: ₱" + df.format(total) + "\n");
            }
            fileWriter.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
        else if(CarBrand.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Please, select a plate number.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_savebtn1ActionPerformed
    
    private void CarBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarBrandActionPerformed
        String Plate;
        ImageIcon carPicIcon = null;
        
        if(CarBrand.getSelectedItem().equals("FORD RANGER RAPTOR")){
            Plate =CarPlate[1].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/bigcar1.png")));
            CarPic.setIcon(carPicIcon);
        }
        else if(CarBrand.getSelectedItem().equals("MITSHUBISHI MONTERO SPORTS")){
            Plate =CarPlate[2].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/bigcar2.png")));
            CarPic.setIcon(carPicIcon);
        }
        else if(CarBrand.getSelectedItem().equals("TOYOTA LAND CRUISER")){
            Plate =CarPlate[3].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/bigcar3_landcruiser.png")));
            CarPic.setIcon(carPicIcon);            
        }
        else if(CarBrand.getSelectedItem().equals("TOYOTA HILUX CONQUEST")){
            Plate =CarPlate[4].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/bigcar4.png"))) ;
            CarPic.setIcon(carPicIcon);           
        }
        else if(CarBrand.getSelectedItem().equals("HONDA CIVIC TYPE-R")){
            Plate =CarPlate[5].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/familycar1.png")));
            CarPic.setIcon(carPicIcon);            
        }
        else if(CarBrand.getSelectedItem().equals("NISSAN ALMERA")){
            Plate =CarPlate[6].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/familycar2.png")));
            CarPic.setIcon(carPicIcon);            
        }
        else if(CarBrand.getSelectedItem().equals("FORD S-MAX")){
            Plate =CarPlate[7].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/familycar3_fordSMAX.png")));
            CarPic.setIcon(carPicIcon);           
        }
        else if(CarBrand.getSelectedItem().equals("TOYOTA VIOS")){
            Plate =CarPlate[8].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/familycar4_vios.png")));
            CarPic.setIcon(carPicIcon);            
        }
        else if(CarBrand.getSelectedItem().equals("TOYOTA HIACE")){
            Plate =CarPlate[9].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/vancar1.png")));
            CarPic.setIcon(carPicIcon);
        }
        else if(CarBrand.getSelectedItem().equals("VOLKSWAGEN VWT1|1950")){
            Plate =CarPlate[10].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/vancar2volkswagen_van.png")));
            CarPic.setIcon(carPicIcon);            
        }
        else if(CarBrand.getSelectedItem().equals("HYUNDAI STAREX")){
            Plate =CarPlate[11].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/vancar3starex.png")));
            CarPic.setIcon(carPicIcon);            
        }
        else if(CarBrand.getSelectedItem().equals("FOTON TRAVELLER XL")){
            Plate =CarPlate[12].toString();
            numberplate1.setText(Plate);
            carPicIcon = new ImageIcon((getClass().getResource("/CarPicture/vancar4_foton_traveler_xl.png")));
            CarPic.setIcon(carPicIcon);            
        }
        else{
            Plate =CarPlate[0].toString();
            numberplate1.setText(Plate);
            CarPic.setIcon(carPicIcon); 
        }
           
    }//GEN-LAST:event_CarBrandActionPerformed
    
    private void dpfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpfieldActionPerformed

    }//GEN-LAST:event_dpfieldActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        if (jTable2.getSelectedRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Please select a row in the [Return Car table] before deleting.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }
        DefaultTableModel model4 = (DefaultTableModel) jTable2.getModel();
        model4.removeRow(jTable2.getSelectedRow());
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
    jDateChooser2.addPropertyChangeListener(new PropertyChangeListener() {
        @Override
        public void propertyChange(PropertyChangeEvent e) {
            Date date2 = jDateChooser2.getDate();
            Date date1 = jDateChooser1.getDate();
            if (date2 != null && date1 != null && date2.before(date1)) {
                jDateChooser2.setDate(date1);
            }
        }
    });
    }//GEN-LAST:event_jDateChooser2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RENT_RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RENT_RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RENT_RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RENT_RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RENT_RETURN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CJ;
    public javax.swing.JComboBox<String> CarBrand;
    private javax.swing.JLabel CarPic;
    private javax.swing.JLabel Carlogo;
    private javax.swing.JLabel carplate1_lbl;
    private javax.swing.JLabel carplate1_lbl1;
    private javax.swing.JLabel carplate1_lbl2;
    private javax.swing.JButton clearbtn1;
    private javax.swing.JLabel date_lbl;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField dpfield;
    private javax.swing.JLabel duedate_lbl;
    private javax.swing.JLabel duedate_lbl1;
    private javax.swing.JButton homebtn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel name1_lbl;
    private javax.swing.JTextField namefield1;
    private javax.swing.JLabel numberplate1;
    private javax.swing.JButton rentablebtn;
    private javax.swing.JLabel rentacar_lbl;
    private javax.swing.JLabel rentacar_lbl1;
    private javax.swing.JButton rentbtn;
    private javax.swing.JButton return1;
    private javax.swing.JLabel returncar_lbl;
    private javax.swing.JButton savebtn1;
    // End of variables declaration//GEN-END:variables
}
