/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalmanagement;


import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Magcalas
 */
public class RENT_RETURN extends javax.swing.JFrame {
    public static String getcostname;
    public static String CarName1;
    public static String[] CarName = {"Name","FORD RANGER RAPTOR","MITSHUBISHI MONTERO SPORTS","TOYOTA LAND CRUISER",
                                             "TOYOTA HILUX CONQUEST","HONDA CIVIC TYPE-R","NISSAN ALMERA","FORD S-MAX",
                                             "TOYOTA VIOS","TOYOTA HIACE","VOLKSWAGEN VWT1|1950","HYUNDAI STAREX",
                                             "FOTON TRAVELLER XL"};
    public static DecimalFormat df = new DecimalFormat("00.00");
    public static Double calcu = 0.0;
    public static Double inputValue = 0.0;
    public static Double total = calcu - inputValue;
    public static String dpay;

    public static int days;
    
    public RENT_RETURN() {
        initComponents();
        jDateChooser2PropertyChange(null);
        this.setTitle("CJ Car Rental Services");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Carlogo = new javax.swing.JLabel();
        CJ = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        rentablebtn = new javax.swing.JButton();
        rentbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        returncar_lbl = new javax.swing.JLabel();
        return1 = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rentacar_lbl = new javax.swing.JLabel();
        carplate1_lbl = new javax.swing.JLabel();
        name1_lbl = new javax.swing.JLabel();
        date_lbl = new javax.swing.JLabel();
        duedate_lbl = new javax.swing.JLabel();
        PlateNo = new javax.swing.JComboBox<>();
        savebtn1 = new javax.swing.JButton();
        clearbtn1 = new javax.swing.JButton();
        namefield1 = new javax.swing.JTextField();
        rentacar_lbl1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        duedate_lbl1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        dpfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        Carlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logopic/Blue_and_Red_Minimalist_Car_Detailing_Logo-removebg-preview.png"))); // NOI18N
        Carlogo.setText("Carlogo");
        Carlogo.setAutoscrolls(true);

        CJ.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        CJ.setText("CJ Car Rental Services");
        CJ.setAutoscrolls(true);

        logoutbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logoutbtn.setText("LOG OUT");
        logoutbtn.setAutoscrolls(true);
        logoutbtn.setContentAreaFilled(false);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        homebtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        homebtn.setText("HOME");
        homebtn.setAutoscrolls(true);
        homebtn.setContentAreaFilled(false);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        rentablebtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rentablebtn.setText("RENTABLES");
        rentablebtn.setAutoscrolls(true);
        rentablebtn.setContentAreaFilled(false);
        rentablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentablebtnActionPerformed(evt);
            }
        });

        rentbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rentbtn.setText("RENT & RETURN A CAR");
        rentbtn.setAutoscrolls(true);
        rentbtn.setContentAreaFilled(false);
        rentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Carlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CJ)
                .addGap(28, 28, 28)
                .addComponent(homebtn)
                .addGap(38, 38, 38)
                .addComponent(rentablebtn)
                .addGap(59, 59, 59)
                .addComponent(rentbtn)
                .addGap(75, 75, 75)
                .addComponent(logoutbtn)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CJ)
                    .addComponent(homebtn)
                    .addComponent(rentablebtn)
                    .addComponent(rentbtn)
                    .addComponent(logoutbtn))
                .addContainerGap())
        );

        jPanel4.setAutoscrolls(true);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Plate no", "Name", "Return Date"
            }
        ));
        jTable2.setDragEnabled(true);
        jScrollPane3.setViewportView(jTable2);

        returncar_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        returncar_lbl.setText("RETURN CAR");

        return1.setText("Return");
        return1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return1ActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(returncar_lbl)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(return1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(deletebtn)
                        .addGap(257, 257, 257))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returncar_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(return1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletebtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setAutoscrolls(true);

        rentacar_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rentacar_lbl.setText("Car Rented");

        carplate1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        carplate1_lbl.setText("Car plate no:");

        name1_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name1_lbl.setText("Customer Name:");

        date_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        date_lbl.setText("Date:");

        duedate_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duedate_lbl.setText("DownPayment:");

        PlateNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "GMK4567", "DAF5208", "FOI6309", "JKQ4230", "PAX3402", "CPY2994", "UZC6965", "STL8196", "BUI8515\t", "SNS1943", "HFQ8671", "NNL902" }));
        PlateNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PlateNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateNoActionPerformed(evt);
            }
        });

        savebtn1.setText("Save");
        savebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtn1ActionPerformed(evt);
            }
        });

        clearbtn1.setText("Clear");
        clearbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtn1ActionPerformed(evt);
            }
        });

        namefield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefield1ActionPerformed(evt);
            }
        });

        rentacar_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rentacar_lbl1.setText("RENT A CAR");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Plate no", "Name", "Date", "Due Date", "DPayment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setDragEnabled(true);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        duedate_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duedate_lbl1.setText("Due Date:");

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });

        dpfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rentacar_lbl)
                .addGap(189, 189, 189))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carplate1_lbl)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(duedate_lbl)
                                        .addComponent(duedate_lbl1))
                                    .addGap(88, 88, 88)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(namefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PlateNo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dpfield, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(savebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(clearbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(name1_lbl)
                                        .addComponent(date_lbl))
                                    .addGap(337, 337, 337))
                                .addComponent(rentacar_lbl1)))
                        .addContainerGap(112, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rentacar_lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carplate1_lbl)
                    .addComponent(PlateNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1_lbl)
                    .addComponent(namefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_lbl)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(duedate_lbl1)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duedate_lbl)
                    .addComponent(dpfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearbtn1)
                    .addComponent(savebtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentacar_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public Double DayGap(){
        Double price2 = 0.0;
        //String CarName1;
        Double[] price1 = {0.0,3500.00,3500.00,120000.00,4000.00,5206.00,2000.00,2500.00,2500.00,4000.00,3931.52,4000.00,7000.00};
        if(PlateNo.getSelectedItem().toString().equals("GMK4567")){
             price2 = price1[1];
             CarName1 = CarName[1];
        }
        else if(PlateNo.getSelectedItem().toString().equals("DAF5208")){
             price2 = price1[2];
             CarName1 = CarName[2];
        }
        else if(PlateNo.getSelectedItem().toString().equals("FOI6309")){
             price2 = price1[3];
             CarName1 = CarName[3];
        }
        else if(PlateNo.getSelectedItem().toString().equals("JKQ4230")){
             price2 = price1[4];
             CarName1 = CarName[4];
        }
        else if(PlateNo.getSelectedItem().toString().equals("PAX3402")){
             price2 = price1[5];
             CarName1 = CarName[5];
        }
        else if(PlateNo.getSelectedItem().toString().equals("CPY2994")){
             price2 = price1[6];
             CarName1 = CarName[6];
        }
        else if(PlateNo.getSelectedItem().toString().equals("UZC6965")){
             price2 = price1[7];
             CarName1 = CarName[7];
        }
        else if(PlateNo.getSelectedItem().toString().equals("STL8196")){
             price2 = price1[8];
             CarName1 = CarName[8];
        }
        else if(PlateNo.getSelectedItem().toString().equals("BUI8515")){
             price2 = price1[9];
             CarName1 = CarName[9];
        }
        else if(PlateNo.getSelectedItem().toString().equals("SNS1943")){
             price2 = price1[10];
             CarName1 = CarName[10];
        }
        else if(PlateNo.getSelectedItem().toString().equals("HFQ8671")){
             price2 = price1[11];
             CarName1 = CarName[11];
        }
        else if(PlateNo.getSelectedItem().toString().equals("NNL902")){
             price2 = price1[12];
             CarName1 = CarName[12];
        }
        return price2;
    }
    public Double renting(Double price3){
      LocalDate startDate = jDateChooser1.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
      LocalDate endDate = jDateChooser2.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
      dpay = dpfield.getText();

      //Double calcu = 0.0;
      //Double inputValue = 0.0;
      //Double total = calcu - inputValue;
      

        days = (int) ChronoUnit.DAYS.between(startDate, endDate);
            if(days >= 1 && days <= 6){
                calcu = price3 * days;
                inputValue = Double.valueOf(dpay);               
                total = calcu - inputValue;
                JOptionPane.showMessageDialog(null, "Rent per day: ₱"+ df.format(price3) +
                                                   "\nTotal Amount to pay: ₱"+ df.format(calcu) + 
                                                   "\nYour Downpayment is: ₱" + dpay + 
                                                   "\nYour remaining balance is: ₱" + df.format(total) + 
                                                   "\nDay Gap: "+ days ,"NOTICE",JOptionPane.INFORMATION_MESSAGE);                      
            }
            else if(days >= 7 && days <= 14){
                Double discount = price3 * 0.2;
                Double discount1 = price3 - discount;
                calcu = discount * days; 
                inputValue = Double.valueOf(dpay);
                total = calcu - inputValue;
                JOptionPane.showMessageDialog(null, "Original rent rate: ₱"+ df.format(price3) + 
                                                    "\nRent per day(20% discount): ₱"+ df.format(discount1) +
                                                    "\nTotal Amount to pay: ₱"+ df.format(calcu) + 
                                                    "\nYour Downpayment is: ₱" + dpay + 
                                                    "\nYour remaining balance is: ₱" + df.format(total) + 
                                                    "\nDay Gap: "+ days ,"NOTICE",JOptionPane.INFORMATION_MESSAGE);
            }
            else if(days >= 15 && days <= 31 || days > 31){
                Double discount = price3 * 0.4;
                Double discount1 = price3 - discount;
                calcu = discount * days;
                inputValue = Double.valueOf(dpay);
                total = calcu - inputValue;
                JOptionPane.showMessageDialog(null, "Original rent rate: ₱"+ df.format(price3) + 
                                                   "\nRent per day(20% discount): ₱"+ df.format(discount1) +
                                                    "\nTotal Amount to pay: ₱"+ df.format(calcu) + 
                                                    "\nYour Downpayment is: ₱" + dpay + 
                                                    "\nYour remaining balance is: ₱" + df.format(total) + 
                                                    "\nDay Gap: "+ days ,"NOTICE",JOptionPane.INFORMATION_MESSAGE);           
            }
            else{
                JOptionPane.showMessageDialog(null,"wow mali","NOTICE",JOptionPane.WARNING_MESSAGE);
            }
            
        try {
            File path = new File("RENT_CAR.txt");
            if (!path.exists()) {
                boolean success = path.createNewFile();
            if (!success) {
            JOptionPane.showMessageDialog(null, "Could not create the file: RENT_CAR.txt", "Error", JOptionPane.ERROR_MESSAGE);
            
            }
        }
             FileWriter filewriter = new FileWriter(path.getAbsoluteFile(),true);
             BufferedWriter bufferedwriter = new BufferedWriter(filewriter);
             bufferedwriter.append("\n///////////////////////");
             bufferedwriter.append("\nCJ Car Rental Services");
             bufferedwriter.append("\n   (Rent a Car)");
             bufferedwriter.append("\n///////////////////////");
             bufferedwriter.append("\nCustomer Name: " + namefield1.getText());
             bufferedwriter.append("\nCar Brand: " + CarName1.toString());
             bufferedwriter.append("\nPlate No.: " + PlateNo.getSelectedItem());
             bufferedwriter.append("\nDownpayment: ₱" + dpay);
             bufferedwriter.append("\nRemaining Balance: ₱" + total);
             bufferedwriter.append("\n///////////////////////\n");            
             bufferedwriter.close();
    } catch (IOException e) {
    JOptionPane.showMessageDialog(null, "Could not write to the file: RENT_CAR.txt", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
    
    }
        return total;
    }
    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        int respond = JOptionPane.showConfirmDialog(null, "Do you wish to exit?","Notice",JOptionPane.YES_NO_OPTION);

        if(respond == JOptionPane.YES_OPTION){
            this.dispose();
            JOptionPane.showConfirmDialog(null, "THANK YOU FOR USING OUR JAVA MENU SYSTEM","Notice",JOptionPane.YES_NO_OPTION);
            LOGIN login = new LOGIN();
            login.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        if(evt.getSource()==homebtn){
            this.dispose();
            HOME home = new HOME();
            home.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_homebtnActionPerformed

    private void rentablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentablebtnActionPerformed
        if(evt.getSource()== rentablebtn){
            this.dispose();
            RENTABLES rentables = new RENTABLES();
            rentables.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_rentablebtnActionPerformed

    private void rentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentbtnActionPerformed
        if(evt.getSource()==rentbtn){
            this.dispose();
            RENT_RETURN rent = new RENT_RETURN();
            rent.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_rentbtnActionPerformed

    private void return1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return1ActionPerformed
        if (jTable1.getSelectedRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Please select a row in [Car Rented Table] before returning.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }

        Double remainblnc1 = 0.0;
        Double remainblnc2 = remainblnc1 - total;

        boolean validInput = false;
        do {
            try {
                String remainblnc = JOptionPane.showInputDialog(null, "The Car has been returned" + "\nRemaining balance: ₱" + df.format(total), "NOTICE", JOptionPane.OK_CANCEL_OPTION);
                remainblnc1 = Double.parseDouble(remainblnc);
                remainblnc2 = remainblnc1 - total;
                validInput = true;
            } 
            catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid number.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } while(!validInput);

        JOptionPane.showMessageDialog(null, "Paid: ₱" + df.format(remainblnc1) 
                                          + "\nChange: ₱" + df.format(remainblnc2) 
                                          + "\nThank you for renting our vehicles!", "NOTICE", JOptionPane.INFORMATION_MESSAGE);

    try {
         File path = new File("RETURN_CAR.txt");
        if(!path.exists()){ 
              path.createNewFile();
    }
        FileWriter filewriter = new FileWriter(path.getAbsoluteFile(),true);
        BufferedWriter bufferedwriter = new BufferedWriter(filewriter);
        bufferedwriter.append("\n///////////////////////");
        bufferedwriter.append("\nCJ Car Rental Services");
        bufferedwriter.append("\n  (Return a Car)");
        bufferedwriter.append("\n///////////////////////");
        bufferedwriter.append("\nCustomer Name: " + jTable1.getValueAt(jTable1.getSelectedRow(), 1) 
                            + "\nCar Brand: " + CarName1.toString() 
                            + "\nPlate No.: " + jTable1.getValueAt(jTable1.getSelectedRow(), 0) 
                            + "\nnPay: ₱" + df.format(remainblnc1)
                            + "\nChange: ₱" + df.format(remainblnc2)); 
        bufferedwriter.append("\n///////////////////////\n");
        bufferedwriter.close();
    } catch (IOException e) {
        e.printStackTrace();
    }

    DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
    model2.addRow(new Object[]{
        jTable1.getValueAt(jTable1.getSelectedRow(), 0),
        jTable1.getValueAt(jTable1.getSelectedRow(), 1),
        jTable1.getValueAt(jTable1.getSelectedRow(), 3)
    });

    DefaultTableModel model3 = (DefaultTableModel) jTable1.getModel();
    model3.removeRow(jTable1.getSelectedRow());

    }//GEN-LAST:event_return1ActionPerformed

    private void namefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefield1ActionPerformed
        
    }//GEN-LAST:event_namefield1ActionPerformed

    private void clearbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtn1ActionPerformed
        PlateNo.setSelectedIndex(0);
        namefield1.setText(" ");
        jDateChooser1.setCalendar(null);
        jDateChooser2.setCalendar(null);
        dpfield.setText("");
    }//GEN-LAST:event_clearbtn1ActionPerformed

    private void savebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtn1ActionPerformed
       
        if(PlateNo.getSelectedIndex() > 0 ){
        Double rentalPrice = DayGap();// get the rental price for the selected car
        renting(rentalPrice); // call the renting() method with the rental price as an argument
        SimpleDateFormat dFormat = new SimpleDateFormat("MMM-dd-yyyy");
        String date = dFormat.format(jDateChooser1.getDate());
        String date2 = dFormat.format(jDateChooser2.getDate());
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{PlateNo.getSelectedItem(), 
                                  namefield1.getText(), 
                                  date, 
                                  date2, 
                                  dpfield.getText(),    
                                  
        });
        clearbtn1ActionPerformed(evt);
      try {
            FileWriter fileWriter = new FileWriter("Rent_Info.txt", true);
            if (total > 0) {
                fileWriter.write(namefield1.getText() + " - Total amount to pay: ₱" + df.format(total) + "\n");
            }
            fileWriter.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
        else if(PlateNo.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(null, "Please, select a plate number.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        else if(PlateNo.getSelectedIndex() > 0 && 1 <= days){
        JOptionPane.showMessageDialog(null, "all goods", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_savebtn1ActionPerformed
    
    private void PlateNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateNoActionPerformed
        //String[] PlateNo = new String[];
        // JComboBox genderOption = new JComboBox(PlateNo);
    }//GEN-LAST:event_PlateNoActionPerformed

    private void dpfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpfieldActionPerformed

    }//GEN-LAST:event_dpfieldActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        if (jTable2.getSelectedRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Please select a row in the [Return Car table] before deleting.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }
        DefaultTableModel model4 = (DefaultTableModel) jTable2.getModel();
        model4.removeRow(jTable2.getSelectedRow());
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
    jDateChooser2.addPropertyChangeListener(new PropertyChangeListener() {
        @Override
        public void propertyChange(PropertyChangeEvent e) {
            Date date2 = jDateChooser2.getDate();
            Date date1 = jDateChooser1.getDate();
            if (date2 != null && date1 != null && date2.before(date1)) {
                jDateChooser2.setDate(date1);
            }
        }
    });
    }//GEN-LAST:event_jDateChooser2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RENT_RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RENT_RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RENT_RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RENT_RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RENT_RETURN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CJ;
    private javax.swing.JLabel Carlogo;
    public javax.swing.JComboBox<String> PlateNo;
    private javax.swing.JLabel carplate1_lbl;
    private javax.swing.JButton clearbtn1;
    private javax.swing.JLabel date_lbl;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField dpfield;
    private javax.swing.JLabel duedate_lbl;
    private javax.swing.JLabel duedate_lbl1;
    private javax.swing.JButton homebtn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel name1_lbl;
    private javax.swing.JTextField namefield1;
    private javax.swing.JButton rentablebtn;
    private javax.swing.JLabel rentacar_lbl;
    private javax.swing.JLabel rentacar_lbl1;
    private javax.swing.JButton rentbtn;
    private javax.swing.JButton return1;
    private javax.swing.JLabel returncar_lbl;
    private javax.swing.JButton savebtn1;
    // End of variables declaration//GEN-END:variables
}
