    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalmanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author Magcalas
 */
public class RENTABLES extends javax.swing.JFrame {

    /**
     * Creates new form Cars
     */
    public RENTABLES() {
        initComponents();
        this.setTitle("CJ Car Rental Services");
    }
    
    public void carinfo(){
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : \n"
                                                + "  Plate no.\t\t    :\n"
                                                + "  Type\t\t    : \n"
                                                + "  Transmission\t    : \n"
                                                + "  Dimension(Length/Height) : \n"
                                                + "  Weight(T-tons)\t    : \n"
                                                + "  Engine Type/Power\t    : \n"
                                                + "  Capacity Seats\t    : \n"
                                                + "  Fuel Type\t\t    : \n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : \n"
                                                + "  Rent 7 to 14 Days\t    : \n"
                                                + "  Rent 15 to 31 Days\t    : ");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orangepanel = new javax.swing.JPanel();
        Carlogo = new javax.swing.JLabel();
        CJ = new javax.swing.JLabel();
        logoutbtn1 = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        rentbtn = new javax.swing.JButton();
        rentablebtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        car_panel = new javax.swing.JPanel();
        bigcar_label = new javax.swing.JLabel();
        bigcar_btn1 = new javax.swing.JButton();
        bigcar_btn2 = new javax.swing.JButton();
        bigcar_btn3 = new javax.swing.JButton();
        bigcar_btn4 = new javax.swing.JButton();
        familycar_label = new javax.swing.JLabel();
        familycar_btn1 = new javax.swing.JButton();
        familycar2_btn = new javax.swing.JButton();
        familycar_btn3 = new javax.swing.JButton();
        familycar_btn4 = new javax.swing.JButton();
        vans_label = new javax.swing.JLabel();
        vancar_btn1 = new javax.swing.JButton();
        vancar_btn2 = new javax.swing.JButton();
        vancar_btn3 = new javax.swing.JButton();
        vancar_btn4 = new javax.swing.JButton();
        details_panel = new javax.swing.JPanel();
        jTextPane1 = new javax.swing.JTextPane();
        jButton13 = new javax.swing.JButton();
        carchoices_label = new javax.swing.JLabel();
        carchoices_label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orangepanel.setBackground(new java.awt.Color(255, 153, 51));

        Carlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logopic/Blue_and_Red_Minimalist_Car_Detailing_Logo-removebg-preview.png"))); // NOI18N
        Carlogo.setText("Carlogo");

        CJ.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        CJ.setText("CJ Car Rental Services");

        logoutbtn1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logoutbtn1.setText("LOG OUT");
        logoutbtn1.setContentAreaFilled(false);
        logoutbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtn1ActionPerformed(evt);
            }
        });

        homebtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        homebtn.setText("HOME");
        homebtn.setContentAreaFilled(false);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        rentbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rentbtn.setText("RENT & RETURN A CAR");
        rentbtn.setContentAreaFilled(false);
        rentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentbtnActionPerformed(evt);
            }
        });

        rentablebtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rentablebtn.setText("RENTABLES");
        rentablebtn.setContentAreaFilled(false);
        rentablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentablebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orangepanelLayout = new javax.swing.GroupLayout(orangepanel);
        orangepanel.setLayout(orangepanelLayout);
        orangepanelLayout.setHorizontalGroup(
            orangepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangepanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Carlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homebtn)
                .addGap(50, 50, 50)
                .addComponent(rentablebtn)
                .addGap(55, 55, 55)
                .addComponent(rentbtn)
                .addGap(44, 44, 44)
                .addComponent(logoutbtn1)
                .addGap(31, 31, 31))
        );
        orangepanelLayout.setVerticalGroup(
            orangepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Carlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(orangepanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(orangepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutbtn1)
                    .addComponent(CJ)
                    .addComponent(homebtn)
                    .addComponent(rentablebtn)
                    .addComponent(rentbtn))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        car_panel.setBackground(new java.awt.Color(255, 255, 255));

        bigcar_label.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bigcar_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bigcar_label.setText("Big Vehicles");

        bigcar_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/bigcar1.png"))); // NOI18N
        bigcar_btn1.setAutoscrolls(true);
        bigcar_btn1.setDefaultCapable(false);
        bigcar_btn1.setFocusable(false);
        bigcar_btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bigcar_btn1.setPreferredSize(new java.awt.Dimension(150, 150));
        bigcar_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigcar_btn1ActionPerformed(evt);
            }
        });

        bigcar_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/bigcar2.png"))); // NOI18N
        bigcar_btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bigcar_btn2.setPreferredSize(new java.awt.Dimension(150, 150));
        bigcar_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigcar_btn2ActionPerformed(evt);
            }
        });

        bigcar_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/big car3_landcruiser.png"))); // NOI18N
        bigcar_btn3.setAutoscrolls(true);
        bigcar_btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bigcar_btn3.setPreferredSize(new java.awt.Dimension(150, 150));
        bigcar_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigcar_btn3ActionPerformed(evt);
            }
        });

        bigcar_btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/bigcar4.png"))); // NOI18N
        bigcar_btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bigcar_btn4.setPreferredSize(new java.awt.Dimension(150, 150));
        bigcar_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigcar_btn4ActionPerformed(evt);
            }
        });

        familycar_label.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        familycar_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        familycar_label.setText("Family Vehicles");

        familycar_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/familycar1.png"))); // NOI18N
        familycar_btn1.setAutoscrolls(true);
        familycar_btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        familycar_btn1.setPreferredSize(new java.awt.Dimension(150, 150));
        familycar_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familycar_btn1ActionPerformed(evt);
            }
        });

        familycar2_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/familycar2.jpg"))); // NOI18N
        familycar2_btn.setAutoscrolls(true);
        familycar2_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        familycar2_btn.setPreferredSize(new java.awt.Dimension(150, 150));
        familycar2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familycar2_btnActionPerformed(evt);
            }
        });

        familycar_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/familycar3_fordSMAX.png"))); // NOI18N
        familycar_btn3.setAutoscrolls(true);
        familycar_btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        familycar_btn3.setPreferredSize(new java.awt.Dimension(150, 150));
        familycar_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familycar_btn3ActionPerformed(evt);
            }
        });

        familycar_btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/familycar4_vios.png"))); // NOI18N
        familycar_btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        familycar_btn4.setPreferredSize(new java.awt.Dimension(150, 150));
        familycar_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familycar_btn4ActionPerformed(evt);
            }
        });

        vans_label.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        vans_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vans_label.setText("Van Vehicles");

        vancar_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/vancar1.png"))); // NOI18N
        vancar_btn1.setAutoscrolls(true);
        vancar_btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vancar_btn1.setPreferredSize(new java.awt.Dimension(150, 150));
        vancar_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vancar_btn1ActionPerformed(evt);
            }
        });

        vancar_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/vancar2volkswagen van.png"))); // NOI18N
        vancar_btn2.setAutoscrolls(true);
        vancar_btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vancar_btn2.setPreferredSize(new java.awt.Dimension(150, 150));
        vancar_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vancar_btn2ActionPerformed(evt);
            }
        });

        vancar_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/vancar3starex.png"))); // NOI18N
        vancar_btn3.setAutoscrolls(true);
        vancar_btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vancar_btn3.setPreferredSize(new java.awt.Dimension(150, 150));
        vancar_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vancar_btn3ActionPerformed(evt);
            }
        });

        vancar_btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarPicture/vancar4 foton traveler xl.png"))); // NOI18N
        vancar_btn4.setAutoscrolls(true);
        vancar_btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vancar_btn4.setPreferredSize(new java.awt.Dimension(150, 150));
        vancar_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vancar_btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout car_panelLayout = new javax.swing.GroupLayout(car_panel);
        car_panel.setLayout(car_panelLayout);
        car_panelLayout.setHorizontalGroup(
            car_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(car_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(car_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bigcar_label, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vans_label, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familycar_label, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(car_panelLayout.createSequentialGroup()
                        .addGroup(car_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bigcar_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(familycar_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(car_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(car_panelLayout.createSequentialGroup()
                                .addComponent(familycar2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(familycar_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(familycar_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(car_panelLayout.createSequentialGroup()
                                .addComponent(bigcar_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bigcar_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bigcar_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(car_panelLayout.createSequentialGroup()
                        .addComponent(vancar_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vancar_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vancar_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vancar_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        car_panelLayout.setVerticalGroup(
            car_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, car_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bigcar_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(car_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, car_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bigcar_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bigcar_btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bigcar_btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigcar_btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(familycar_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(car_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(familycar_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familycar2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familycar_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familycar_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(vans_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(car_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vancar_btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vancar_btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vancar_btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vancar_btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(223, 223, 223))
        );

        details_panel.setBackground(new java.awt.Color(255, 153, 0));
        details_panel.setAutoscrolls(true);

        jTextPane1.setEditable(false);

        jButton13.setBackground(new java.awt.Color(255, 153, 204));
        jButton13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton13.setText("RESET");
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        carchoices_label.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        carchoices_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carchoices_label.setText("VEHICLE DETAILS");

        javax.swing.GroupLayout details_panelLayout = new javax.swing.GroupLayout(details_panel);
        details_panel.setLayout(details_panelLayout);
        details_panelLayout.setHorizontalGroup(
            details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(details_panelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, details_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, details_panelLayout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, details_panelLayout.createSequentialGroup()
                        .addComponent(carchoices_label)
                        .addGap(163, 163, 163))))
        );
        details_panelLayout.setVerticalGroup(
            details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, details_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carchoices_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        carchoices_label1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        carchoices_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carchoices_label1.setText("VEHICLE CHOICES");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(car_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(details_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(235, 235, 235)
                    .addComponent(carchoices_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(694, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(details_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(car_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(carchoices_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(903, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orangepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(orangepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vancar_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vancar_btn4ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : FOTON TRAVELLER XL\n"
                                                + "  Plate no.\t\t    : NNL902\n"
                                                + "  Type\t\t    : Van Vehicle / Panel Van\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 5,990mm / 2,320mm\n"
                                                + "  Weight(T-tons)\t    :4.4T\n"
                                                + "  Engine Type/Power\t    :  Euro IV/ 148jp \n"
                                                + "  Capacity Seats\t    : 19\n"
                                                + "  Fuel Type\t\t    : Diesel\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱7,000.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱5,600.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱4,200.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_vancar_btn4ActionPerformed

    private void vancar_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vancar_btn3ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : HYUNDAI STAREX\n"
                                                + "  Plate no.\t\t    : HFQ8671\n"
                                                + "  Type\t\t    : Van Vehicle / Commercial Van\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 5,150mm / 1,920mm\n"
                                                + "  Weight(T-tons)\t    : 3.3T\n"
                                                + "  Engine Type/Power\t    : 2.5L CRDi VGT DOHC 16V / 143hp\n"
                                                + "  Capacity Seats\t    : 10\n"
                                                + "  Fuel Type\t\t    : Diesel\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱4,000.00 - Day \n"
                                                + "  Rent 7 to 14 Days\t    : ₱3,200.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱2,400.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_vancar_btn3ActionPerformed

    private void vancar_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vancar_btn2ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : VOLKSWAGEN VWT1|1950\n"
                                                + "  Plate no.\t\t    : SNS1943\n"
                                                + "  Type\t\t    : Van Vehicle / Microbus\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 4,140mm / 1,950mm\n"
                                                + "  Weight(T-tons)\t    : 1.4T\n"
                                                + "  Engine Type/Power\t    : Flat 4 / 52hp\n"
                                                + "  Capacity Seats\t    : 8\n"
                                                + "  Fuel Type\t\t    : Diesel\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱3,931.52 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱3,145.22 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱2,358.90 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_vancar_btn2ActionPerformed

    private void vancar_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vancar_btn1ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : TOYOTA HIACE\n"
                                                + "  Plate no.\t\t    : BUI8515\n"
                                                + "  Type\t\t    : Van Vehicle / Commercial Van\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 5,265mm / 1,990mm\n"
                                                + "  Weight(T-tons)\t    : 2.9T\n"
                                                + "  Engine Type/Power\t    : V6 / 174hp\n"
                                                + "  Capacity Seats\t    : 12\n"
                                                + "  Fuel Type\t\t    : Diesel\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱4,000.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱3,200.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱2,400.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_vancar_btn1ActionPerformed

    private void familycar_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familycar_btn4ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : TOYOTA VIOS\n"
                                                + "  Plate no.\t\t    : STL8196\n"
                                                + "  Type\t\t    : Family Vehicle / Sedan Car\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 4,425mm / 1,475mm\n"
                                                + "  Weight(T-tons)\t    : 1.6T\n"
                                                + "  Engine Type/Power\t    : Dual VVT-I / 106hp\n"
                                                + "  Capacity Seats\t    : 5\n"
                                                + "  Fuel Type\t\t    : Unleaded (95)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱2,500.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱2,000.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱1,500.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_familycar_btn4ActionPerformed

    private void familycar_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familycar_btn3ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : FORD S-MAX\n"
                                                + "  Plate no.\t\t    : UZC6965\n"
                                                + "  Type\t\t    : Family Vehicle / Hatchback Car\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 4,796mm / 1,655mm \n"
                                                + "  Weight(T-tons)\t    : 2.8T\n"
                                                + "  Engine Type/Power\t    : Internal Combustion Engine / 210hp\n"
                                                + "  Capacity Seats\t    : 5\n"
                                                + "  Fuel Type\t\t    : Diesel\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱2,500.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱2,000.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱1,500.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_familycar_btn3ActionPerformed

    private void familycar2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familycar2_btnActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : NISSAN ALMERA\n"
                                                + "  Plate no.\t\t    : CPY2994\n"
                                                + "  Type\t\t    : Family Vehicle / Sedan Car\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 4,495mm / 1,460mm\n"
                                                + "  Weight(T-tons)\t    : 2T\n"
                                                + "  Engine Type/Power\t    : In-Line 3 / 99hp\n"
                                                + "  Capacity Seats\t    : 5\n"
                                                + "  Fuel Type\t\t    : Unleaded (95)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱2,000.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱1,600.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱1,200.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_familycar2_btnActionPerformed

    private void familycar_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familycar_btn1ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : HONDA CIVIC TYPE-R\n"
                                                + "  Plate no.\t\t    : PAX3402\n"
                                                + "  Type\t\t    : Family Vehicle / Sports Car\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 4,594mm / 1,890mm\n"
                                                + "  Weight(T-tons)\t    : 2T\n"
                                                + "  Engine Type/Power\t    : Internal Combustion Engine / 315hp\n"
                                                + "  Capacity Seats\t    : 4\n"
                                                + "  Fuel Type\t\t    : Unleaded (98)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱5,206.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱4,164.80 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱3,123.60 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_familycar_btn1ActionPerformed

    private void bigcar_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigcar_btn4ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : TOYOTA HILUX CONQUEST\n"
                                                + "  Plate no.\t\t    : JKQ4230\n"
                                                + "  Type\t\t    : Big Vehicle / Pickup\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 5,320mm / 2,020mm\n"
                                                + "  Weight(T-tons)\t    : 3T\n"
                                                + "  Engine Type/Power\t    : 2.8-liter 4-cylinder / 148hp\n"
                                                + "  Capacity Seats\t    : 5\n"
                                                + "  Fuel Type\t\t    : Diesel\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱4,000.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱3,200.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱2,400.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_bigcar_btn4ActionPerformed

    private void bigcar_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigcar_btn3ActionPerformed
         jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : TOYOTA LAND CRUISER\n"
                                                + "  Plate no.\t\t    : FOI6309\n"
                                                + "  Type\t\t    : Big Vehicle / SUV\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 5,130mm / 1,980mm \n"
                                                + "  Weight(T-tons)\t    : 2.6T\n"
                                                + "  Engine Type/Power\t    : V6 /302 hp\n"
                                                + "  Capacity Seats\t    : 7\n"
                                                + "  Fuel Type\t\t    : Diesel\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱120,000.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱96,000.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱72,000.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");  
    }//GEN-LAST:event_bigcar_btn3ActionPerformed

    private void bigcar_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigcar_btn2ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : MITSHUBISHI MONTERO SPORTS\n"
                                                + "  Plate no.\t\t    : DAF5208\n"
                                                + "  Type\t\t    : Big Vehicle / SUV\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 4,785 mm / 1,815 mm\n"
                                                + "  Weight(T-tons)\t    : 3T\n"
                                                + "  Engine Type/Power\t    : 2.4-liter 4-cylinder / 178 hp\n"
                                                + "  Capacity Seats\t    : 7\n"
                                                + "  Fuel Type\t\t    : Diesel\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The rates decreasing price for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱3,500.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱2,800.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱2,100.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n"); 
    }//GEN-LAST:event_bigcar_btn2ActionPerformed

    private void bigcar_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigcar_btn1ActionPerformed
        jTextPane1.setText("\t                  CJ Car Rental Services'™\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                  CAR SPECIFICATIONS \n"
                                                + "---------------------------------------------------------------------------------------------\n"
                                                + "  Brand\t\t    : FORD RANGER RAPTOR\n"
                                                + "  Plate no.\t\t    :GMK4567\n"
                                                + "  Type\t\t    : Big Vehicle / Pickup\n"
                                                + "  Transmission\t    : AUTOMATIC/MANUAL\n"
                                                + "  Dimension(Length/Height) : 5,363 mm / 1,873 mm\n"
                                                + "  Weight(T-tons)\t    : 3.4T\n"
                                                + "  Engine Type/Power\t    : V6 / 292 hp\n"
                                                + "  Capacity Seats\t    : 5\n"
                                                + "  Fuel Type\t\t    : Petrol\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t                           RENT RATE \n");
        jTextPane1.setText(jTextPane1.getText() + "               (P.S: The price rates decrease for longer rentals.)\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");   
        jTextPane1.setText(jTextPane1.getText() + "  Rent 1 to 6 Days\t    : ₱3,500.00 - Day\n"
                                                + "  Rent 7 to 14 Days\t    : ₱2,800.00 - Day (20% DISCOUNT)\n"
                                                + "  Rent 15 above Days\t    : ₱2,100.00 - Day (40% DISCOUNT)\n");
        jTextPane1.setText(jTextPane1.getText() + "\n\n\n\n\n\n");
        jTextPane1.setText(jTextPane1.getText() + "---------------------------------------------------------------------------------------------\n");
        jTextPane1.setText(jTextPane1.getText() + "\t\t       Contact Us:\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Phone: +639604041204\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Gmail: CJrent@gmail.com\n");
        jTextPane1.setText(jTextPane1.getText() + "\t            Fb Page: CJ Car Rental Services\n");
    }//GEN-LAST:event_bigcar_btn1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        carinfo();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void logoutbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtn1ActionPerformed
        int respond = JOptionPane.showConfirmDialog(null, "Do you wish to exit?","Notice",JOptionPane.YES_NO_OPTION);

        if(respond == JOptionPane.YES_OPTION){
            this.dispose();
            JOptionPane.showConfirmDialog(null, "THANK YOU FOR USING OUR JAVA MENU SYSTEM","Notice",JOptionPane.YES_NO_OPTION);
            LOGIN login = new LOGIN();
            login.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_logoutbtn1ActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        if(evt.getSource()==homebtn){
            this.dispose();
            HOME home = new HOME();
            home.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_homebtnActionPerformed

    private void rentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentbtnActionPerformed
        if(evt.getSource()==rentbtn){
            this.dispose();
            RENT_RETURN rent = new RENT_RETURN();
            rent.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_rentbtnActionPerformed

    private void rentablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentablebtnActionPerformed
        if(evt.getSource()== rentablebtn){
            this.dispose();
            RENTABLES rentables = new RENTABLES();
            rentables.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_rentablebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RENTABLES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RENTABLES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RENTABLES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RENTABLES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RENTABLES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CJ;
    private javax.swing.JLabel Carlogo;
    private javax.swing.JButton bigcar_btn1;
    private javax.swing.JButton bigcar_btn2;
    private javax.swing.JButton bigcar_btn3;
    private javax.swing.JButton bigcar_btn4;
    private javax.swing.JLabel bigcar_label;
    private javax.swing.JPanel car_panel;
    private javax.swing.JLabel carchoices_label;
    private javax.swing.JLabel carchoices_label1;
    private javax.swing.JPanel details_panel;
    private javax.swing.JButton familycar2_btn;
    private javax.swing.JButton familycar_btn1;
    private javax.swing.JButton familycar_btn3;
    private javax.swing.JButton familycar_btn4;
    private javax.swing.JLabel familycar_label;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton jButton13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton logoutbtn1;
    private javax.swing.JPanel orangepanel;
    private javax.swing.JButton rentablebtn;
    private javax.swing.JButton rentbtn;
    private javax.swing.JButton vancar_btn1;
    private javax.swing.JButton vancar_btn2;
    private javax.swing.JButton vancar_btn3;
    private javax.swing.JButton vancar_btn4;
    private javax.swing.JLabel vans_label;
    // End of variables declaration//GEN-END:variables

}

